### ISSUE TITLE
Add macro to find sanitizer libraries

### ISSUE THREAD

**Issue by constreference** [VerizonDigital/hurl#31]
Add macro to find sanitizer libraries on Linux
The integration with fail_if_not_found macro was listed as a TODO, it would be better to add a separate macro to find the sanitizer libraries since it's a good use case to match against multiple libraries as opposed to one (giving precedence to an unversioned one)

**Comment by constreference** [comment]
When the library is not found, debug is as follows when the libraries are missing, 

```
CMake Error at CMakeLists.txt:61 (message):
  asan library not found

Call Stack (most recent call first):
  CMakeLists.txt:84 (fail_if_not_found_sanitizers)
```

```
CMake Error at CMakeLists.txt:61 (message):
  ubsan library not found

Call Stack (most recent call first):
  CMakeLists.txt:98 (fail_if_not_found_sanitizers)
```

Platform: CentOS

Could not test the negative case on Ubuntu as the compiler tool-chain installs sanitizer libraries by default

**Comment by tinselcity** [comment]
It seems fine as is -really appreciate the contribution!  Thanks -I can work on add CentOS to the GitHub CI Actions if possible.
